### ISSUE TITLE
step 5 doesn't have a procedure

### ISSUE THREAD

**Issue by ldonofrio** [rohitsies/GNAF-SSIS-Data-Loader#6]
step 5 says "Download and execute script attached to this gitub account named BulkImportDataSP.sql. This creates stored procedure to bulk import data which is used by SSIS package"

the BulkImportDataSP.sql is the  same code in step 4. address_view.sql creating the view no package

**Comment by rohitsies** [comment]
Nope both are separate
Step 4 mentions about running the sql from Extra folder which you need to download in step 1
and Step 5 is for running .sql in the github account.
The reason why these are separate steps are because GNAF dataset comes with its own sql queries and it might change over time due to which I haven't uploaded that, you need to download the latest.
BulkImportDataSP.sql is sql stored proc which bulk inserts data from csv to sql.
Hope that clears.
